<?php
// CREO UNA VARIABLE PARA GUARDAR LOS VALORES NECESARIOS PARA LA CONEXION
// LOS VALORES SON "HOST" "USUARIO" "CONTRASEÑA" "NOMBRE_BASE_DATOS"
// SI LA CONEXION FALLA DEVUELVE EL ERROR ESPECIFICO 
    $conexion = mysqli_connect("HOST", "USUARIO", "CONTRASEÑA", "NOMBRE_BASE_DATOS") 
    or die ("No se pudo conectar" . mysql_error($conexion));
?>
